### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Kevun1** [mujmajnkraft/BetterSurvival#3]
A crash after attacking an entity with a regular diamond sword, on version 1.3.2:

java.lang.IllegalArgumentException: Modifier is already applied on this attribute!
	at net.minecraft.entity.ai.attributes.ModifiableAttributeInstance.func_111121_a(SourceFile:89)
	at com.mujmajnkraft.bettersurvival.eventhandlers.ModWeaponHandler.onEvent(ModWeaponHandler.java:163)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1718_ModWeaponHandler_onEvent_LivingUpdateEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:554)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2082)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:388)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java:50)
	at net.minecraft.entity.monster.EntitySpider.func_70071_h_(SourceFile:87)
	at net.minecraft.world.World.func_72866_a(World.java:1986)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:831)
	at net.minecraft.world.World.func_72870_g(World.java:1948)
	at net.minecraft.world.World.func_72939_s(World.java:1755)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:239)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)

**Comment by Block-Vader** [comment]
This should be fixed by now.
